### ISSUE TITLE
Recycle TypedArray

### ISSUE THREAD

**Issue by pocmo** [walkingice/Progressbar#6]
AS complains that the TypedArray should be recycled after usage.

**Comment by pocmo** [comment]
Patch in Focus:
https://github.com/mozilla-mobile/focus-android/commit/d226d3efdbcf954e9e4d418a3aa852da47800bce

**Comment by walkingice** [comment]
Fixed in commit
https://github.com/walkingice/Progressbar/commit/d1560173276e1cf48d082597645b3c25a9ec1fad#diff-bf06b5a4e976e24df2e7d0ee7112046cR179

I do need to run code analyze! D'oh
